// Copyright (c) 2026 Egonex S.R.L.
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.
using System.Buffers.Binary;
using System.Text;

namespace ECP.Cascade.Confirmation;

/// <summary>
/// Confirmation status types.
/// </summary>
public enum ConfirmationType : byte
{
    /// <summary>Delivered to the device.</summary>
    Delivered = 0,
    /// <summary>Displayed to the user.</summary>
    Displayed = 1,
    /// <summary>Read by the user.</summary>
    Read = 2,
    /// <summary>Action completed by the user.</summary>
    Actioned = 3
}

/// <summary>
/// Confirmation generated by a single recipient.
/// </summary>
public sealed record SingleConfirmation
{
    private const byte FormatVersion = 1;
    private const int TruncatedHmacLength = 4;
    /// <summary>Recipient identifier.</summary>
    public string RecipientId { get; }
    /// <summary>Confirmation timestamp (UTC).</summary>
    public DateTimeOffset ConfirmedAt { get; }
    /// <summary>Confirmation type.</summary>
    public ConfirmationType Type { get; }
    /// <summary>Truncated HMAC (4 bytes).</summary>
    public ReadOnlyMemory<byte> TruncatedHmac { get; }

    /// <summary>
    /// Creates a confirmation from a single recipient.
    /// </summary>
    public SingleConfirmation(string recipientId, DateTimeOffset confirmedAt, ConfirmationType type, byte[] truncatedHmac)
    {
        if (string.IsNullOrWhiteSpace(recipientId))
        {
            throw new ArgumentException("Recipient id must be provided.", nameof(recipientId));
        }

        ArgumentNullException.ThrowIfNull(truncatedHmac);

        if (truncatedHmac.Length != TruncatedHmacLength)
        {
            throw new ArgumentOutOfRangeException(nameof(truncatedHmac), "Truncated HMAC must be 4 bytes.");
        }

        RecipientId = recipientId;
        ConfirmedAt = confirmedAt;
        Type = type;
        TruncatedHmac = truncatedHmac.ToArray();
    }

    /// <summary>
    /// Serializes the confirmation to bytes (versioned).
    /// </summary>
    public byte[] ToBytes()
    {
        var recipientBytes = Encoding.UTF8.GetBytes(RecipientId);
        if (recipientBytes.Length > ushort.MaxValue)
        {
            throw new ArgumentOutOfRangeException(nameof(RecipientId), "Recipient id is too long.");
        }

        var totalLength = 1 + 1 + 8 + 2 + recipientBytes.Length + TruncatedHmacLength;
        var bytes = new byte[totalLength];
        var span = bytes.AsSpan();

        span[0] = FormatVersion;
        span[1] = (byte)Type;
        BinaryPrimitives.WriteInt64BigEndian(span.Slice(2, 8), ConfirmedAt.ToUnixTimeSeconds());
        BinaryPrimitives.WriteUInt16BigEndian(span.Slice(10, 2), (ushort)recipientBytes.Length);
        recipientBytes.CopyTo(span.Slice(12, recipientBytes.Length));
        TruncatedHmac.Span.CopyTo(span.Slice(12 + recipientBytes.Length, TruncatedHmacLength));

        return bytes;
    }

    /// <summary>
    /// Deserializes a confirmation from bytes (versioned).
    /// </summary>
    public static SingleConfirmation FromBytes(ReadOnlySpan<byte> bytes)
    {
        var confirmation = ReadFrom(bytes, out var bytesRead);
        if (bytesRead != bytes.Length)
        {
            throw new ArgumentException("Unexpected trailing bytes in confirmation payload.", nameof(bytes));
        }

        return confirmation;
    }

    internal static SingleConfirmation ReadFrom(ReadOnlySpan<byte> bytes, out int bytesRead)
    {
        const int headerSize = 1 + 1 + 8 + 2;
        if (bytes.Length < headerSize + TruncatedHmacLength)
        {
            throw new ArgumentException("Confirmation payload is too short.", nameof(bytes));
        }

        var version = bytes[0];
        if (version != FormatVersion)
        {
            throw new ArgumentOutOfRangeException(nameof(bytes), $"Unsupported confirmation format version {version}.");
        }

        var type = (ConfirmationType)bytes[1];
        var timestampSeconds = BinaryPrimitives.ReadInt64BigEndian(bytes.Slice(2, 8));
        var recipientLength = BinaryPrimitives.ReadUInt16BigEndian(bytes.Slice(10, 2));
        var totalLength = headerSize + recipientLength + TruncatedHmacLength;
        if (bytes.Length < totalLength)
        {
            throw new ArgumentException("Confirmation payload is truncated.", nameof(bytes));
        }

        var recipientId = Encoding.UTF8.GetString(bytes.Slice(12, recipientLength));
        var hmacStart = 12 + recipientLength;
        var hmac = bytes.Slice(hmacStart, TruncatedHmacLength).ToArray();

        bytesRead = totalLength;
        return new SingleConfirmation(recipientId, DateTimeOffset.FromUnixTimeSeconds(timestampSeconds), type, hmac);
    }
}

/// <summary>
/// Aggregated confirmation from multiple recipients.
/// </summary>
public sealed record AggregatedConfirmation
{
    private const byte FormatVersion = 1;
    /// <summary>Original message identifier.</summary>
    public ulong OriginalMessageId { get; }
    /// <summary>Aggregation timestamp (UTC).</summary>
    public DateTimeOffset AggregatedAt { get; }
    /// <summary>Node that aggregated confirmations.</summary>
    public string AggregatorNodeId { get; }
    /// <summary>Aggregated confirmations.</summary>
    public IReadOnlyList<SingleConfirmation> Confirmations { get; }

    /// <summary>
    /// Creates an aggregated confirmation package.
    /// </summary>
    public AggregatedConfirmation(
        ulong originalMessageId,
        DateTimeOffset aggregatedAt,
        string aggregatorNodeId,
        IReadOnlyList<SingleConfirmation> confirmations)
    {
        if (string.IsNullOrWhiteSpace(aggregatorNodeId))
        {
            throw new ArgumentException("Aggregator node id must be provided.", nameof(aggregatorNodeId));
        }

        ArgumentNullException.ThrowIfNull(confirmations);
        Confirmations = confirmations;
        OriginalMessageId = originalMessageId;
        AggregatedAt = aggregatedAt;
        AggregatorNodeId = aggregatorNodeId;
    }

    /// <summary>
    /// Serializes the aggregated confirmation to bytes (versioned).
    /// </summary>
    public byte[] ToBytes()
    {
        if (Confirmations.Count > ushort.MaxValue)
        {
            throw new ArgumentOutOfRangeException(nameof(Confirmations), "Too many confirmations to serialize.");
        }

        var aggregatorBytes = Encoding.UTF8.GetBytes(AggregatorNodeId);
        if (aggregatorBytes.Length > ushort.MaxValue)
        {
            throw new ArgumentOutOfRangeException(nameof(AggregatorNodeId), "Aggregator node id is too long.");
        }

        var totalLength = 1 + 8 + 8 + 2 + aggregatorBytes.Length + 2;
        foreach (var confirmation in Confirmations)
        {
            totalLength += confirmation.ToBytes().Length;
        }

        var bytes = new byte[totalLength];
        var span = bytes.AsSpan();
        var offset = 0;

        span[offset++] = FormatVersion;
        BinaryPrimitives.WriteUInt64BigEndian(span.Slice(offset, 8), OriginalMessageId);
        offset += 8;
        BinaryPrimitives.WriteInt64BigEndian(span.Slice(offset, 8), AggregatedAt.ToUnixTimeSeconds());
        offset += 8;
        BinaryPrimitives.WriteUInt16BigEndian(span.Slice(offset, 2), (ushort)aggregatorBytes.Length);
        offset += 2;
        aggregatorBytes.CopyTo(span.Slice(offset, aggregatorBytes.Length));
        offset += aggregatorBytes.Length;
        BinaryPrimitives.WriteUInt16BigEndian(span.Slice(offset, 2), (ushort)Confirmations.Count);
        offset += 2;

        foreach (var confirmation in Confirmations)
        {
            var confirmationBytes = confirmation.ToBytes();
            confirmationBytes.CopyTo(span.Slice(offset, confirmationBytes.Length));
            offset += confirmationBytes.Length;
        }

        return bytes;
    }

    /// <summary>
    /// Deserializes an aggregated confirmation from bytes (versioned).
    /// </summary>
    public static AggregatedConfirmation FromBytes(ReadOnlySpan<byte> bytes)
    {
        const int headerSize = 1 + 8 + 8 + 2 + 2;
        if (bytes.Length < headerSize)
        {
            throw new ArgumentException("Aggregated confirmation payload is too short.", nameof(bytes));
        }

        var version = bytes[0];
        if (version != FormatVersion)
        {
            throw new ArgumentOutOfRangeException(nameof(bytes), $"Unsupported aggregated format version {version}.");
        }

        var offset = 1;
        var originalMessageId = BinaryPrimitives.ReadUInt64BigEndian(bytes.Slice(offset, 8));
        offset += 8;
        var timestampSeconds = BinaryPrimitives.ReadInt64BigEndian(bytes.Slice(offset, 8));
        offset += 8;
        var aggregatorLength = BinaryPrimitives.ReadUInt16BigEndian(bytes.Slice(offset, 2));
        offset += 2;

        if (bytes.Length < offset + aggregatorLength + 2)
        {
            throw new ArgumentException("Aggregated confirmation payload is truncated.", nameof(bytes));
        }

        var aggregatorNodeId = Encoding.UTF8.GetString(bytes.Slice(offset, aggregatorLength));
        offset += aggregatorLength;

        var count = BinaryPrimitives.ReadUInt16BigEndian(bytes.Slice(offset, 2));
        offset += 2;

        var confirmations = new List<SingleConfirmation>(count);
        for (var i = 0; i < count; i++)
        {
            var confirmation = SingleConfirmation.ReadFrom(bytes.Slice(offset), out var bytesRead);
            confirmations.Add(confirmation);
            offset += bytesRead;
        }

        if (offset != bytes.Length)
        {
            throw new ArgumentException("Unexpected trailing bytes in aggregated confirmation payload.", nameof(bytes));
        }

        return new AggregatedConfirmation(
            originalMessageId,
            DateTimeOffset.FromUnixTimeSeconds(timestampSeconds),
            aggregatorNodeId,
            confirmations);
    }
}
